//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class users
    {
        public int id { get; set; }

        [Display(Name="Username")]
        [Required(ErrorMessage="Veuillez saisir le username !")]
        public string username { get; set; }

        [Display(Name ="Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Veuillez saisir le mot de passe !")]
        public string passwords { get; set; }

        [Display(Name ="Repassword")]
        [Required(ErrorMessage ="Veuillez saisir le champ !")]
        [Compare("passwords", ErrorMessage = "Confirmer le mot de passe !")]
        [DataType(DataType.Password)]
        [NotMapped]
        public string Repasswords { get; set; }
    }
}
